name: Package BAIN Installer

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create folders and copy files
      run: |
        mkdir -p "00 DART Core (Required)/gamedata"
        mkdir -p "01 Minimap Fixes/gamedata"
        mkdir -p "02 Map Marker Fixes/gamedata"
        mkdir -p "03 Inventory Fixes/gamedata"
        mkdir -p "04 Wheel UI Fixes/gamedata"
        mkdir -p "05 Scope Fixes/gamedata"
        mkdir -p "06 Faction ID Patch Fixes/gamedata"
        mkdir -p "07 Mask Tweaks (from GIRTH)/gamedata"
        mkdir -p "08 Health HUD/gamedata"
        mkdir -p "09 News Fixes/gamedata"
        mkdir -p "10 Indicator Fixes (aliticons)/gamedata"

        cp -R gamedata/scripts/DART.script gamedata/scripts/zzz_dart_config.script "00 DART Core (Required)/gamedata/"
        cp -R gamedata/scripts/modxml_dart_minimap.script "01 Minimap Fixes/gamedata/"
        cp -R gamedata/scripts/modxml_dart_markers.script "02 Map Marker Fixes/gamedata/"
        cp -R gamedata/scripts/z_dart_inventory.script "03 Inventory Fixes/gamedata/"
        cp -R gamedata/scripts/modxml_dart_ammo_wheel.script gamedata/scripts/modxml_dart_companion_wheel.script "04 Wheel UI Fixes/gamedata/"
        cp -R gamedata/scripts/modxml_dart_scopes.script gamedata/textures/wpn/wpn_crosshair_bino.dds "05 Scope Fixes/gamedata/"
        cp -R gamedata/scripts/factionID_hud_mcm.script gamedata/scripts/modxml_dart_patches.script "06 Faction ID Patch Fixes/gamedata/"
        cp -R gamedata/shaders/r3/gasmask* "07 Mask Tweaks (from GIRTH)/gamedata/"
        cp -R gamedata/scripts/modxml_dart_health_hud.script "08 Health HUD/gamedata/"
        cp -R gamedata/configs/ui/maingame_pda_msg* gamedata/scripts/modxml_dart_news.script "09 News Fixes/gamedata/"
        cp -R gamedata/scripts/z_alticons.script "10 Indicator Fixes (aliticons)/gamedata/"
        

    - name: Archive files
      run: |
        7z a -r release.7z gamedata

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.7z
        asset_name: release.7z
        asset_content_type: application/x-7z-compressed